version: "3.8"

networks:
  shared_network:
    driver: bridge

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:4.0.3
    ports:
      - "4510-4559:4510-4559"  # Service port range
      - "4566:4566"            # LocalStack Edge Proxy
    environment:
      - LOCALSTACK_HOST=localhost.localstack.cloud
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_DEFAULT_REGION=eu-west-1
      - LAMBDA_EXECUTOR=docker  # Required for Java Lambdas
      - SERVICES=cloudformation,s3,dynamodb,sns,sqs,lambda,events,iam,cloudwatch,stepfunctions
      - DEBUG=true              # Enable debug logs
    volumes:
      - "./tmp/localstack:/var/lib/localstack"  # Persistent state
      - "/var/run/docker.sock:/var/run/docker.sock"  # Lambda execution in Docker
    networks:
      - shared_network
    extra_hosts:
      - "localhost.localstack.cloud:127.0.0.1"  # Alias for LocalStack
    deploy:
      resources:
        limits:
          memory: 2g  # Limit container to 1 GB of memory
        reservations:
          memory: 512m  # Reserve 512 MB of memory for this container
