AWSTemplateFormatVersion: "2010-09-09"

Resources:
  OrderTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "orders"
      BillingMode: "PAY_PER_REQUEST"
      DeletionPolicy: "Retain"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "category"
          AttributeType: "S"
        - AttributeName: "order-date"
          AttributeType: "S"
        - AttributeName: "query-slot-mod64"
          AttributeType: "N"
        - AttributeName: "query-slot-mod128"
          AttributeType: "N"
        - AttributeName: "payment-type"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "category-order-date-index"
          KeySchema:
            - AttributeName: "category"
              KeyType: "HASH"
            - AttributeName: "order-date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "category-query-slot-mod64-index"
          KeySchema:
            - AttributeName: "category"
              KeyType: "HASH"
            - AttributeName: "query-slot-mod64"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "category-query-slot-mod128-index"
          KeySchema:
            - AttributeName: "category"
              KeyType: "HASH"
            - AttributeName: "query-slot-mod128"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "payment-type-index"
          KeySchema:
            - AttributeName: "payment-type"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
  ConsumedEventsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "consumedEvents"
      BillingMode: "PAY_PER_REQUEST"
      DeletionPolicy: "Retain"
      AttributeDefinitions:
        - AttributeName: "orderId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "orderId"
          KeyType: "HASH"
