AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for SQS, DynamoDB, and Lambda with event source mapping.

Resources:
  # SQS Queue
  ProductQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: product-sqs-queue

#  # DynamoDB Table
#  OrderTable:
#    Type: AWS::DynamoDB::Table
#    Properties:
#      TableName: order
#      AttributeDefinitions:
#        - AttributeName: id
#          AttributeType: S
#        - AttributeName: productNumber
#          AttributeType: S
#      KeySchema:
#        - AttributeName: id
#          KeyType: HASH  # Partition key
#        - AttributeName: productNumber
#          KeyType: RANGE  # Sort key
#      BillingMode: PAY_PER_REQUEST

  # IAM Role for Lambda
  OrderLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: OrderLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: OrderLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                Resource: "*"

  # Lambda Function
  OrderLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: OrderSQSProcessor
      Runtime: java17
      Handler: io.awssample.handler.SQSLockHandler::handleRequest
      Code:
        S3Bucket: artifact-storage-bucket
        S3Key: order-sync-lambda-1.0-SNAPSHOT.jar
      MemorySize: 512
      Timeout: 60
      Role: !GetAtt OrderLambdaExecutionRole.Arn
      Environment:
        Variables:
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: key
          AWS_SECRET_ACCESS_KEY: secret
          ORDER_TABLE_NAME: order

  # Lambda Event Source Mapping
  SQSToOrderLambdaMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt ProductQueue.Arn
      FunctionName: !Ref OrderLambdaFunction
      BatchSize: 5
      Enabled: true
